#!/bin/bash

handle_command() {
  if [[ $1 == "start" ]]; then
    start_environment "$2"
  fi

  if [[ $1 == "stop" ]]; then
    stop_environment
  fi

  if [[ $1 == "clean" ]]; then
    clean_environment
  fi

  print_manual
}

print_manual() {
  echo "Letstur"
  echo ""
  echo "Available arguments:"
  echo -e "\e[32mstart\e[39m\tStarts the environment"
  echo -e "\e[32mstop\e[39m\tStops the environment"
  echo -e "\e[32mclean\e[39m\tDown the environment, clean orphans and remove network."
}

start_environment() {
  echo -e "[\e[33mWAIT\e[39m] Starting development environment"

  docker compose -f docker-compose.yaml stop
  docker compose -f docker-compose.yaml up -d --remove-orphans --force-recreate

  if [ $? -eq 0 ]; then
    echo -e "[\e[32mOK\e[39m] Environment started"
  else
    echo -e "[\e[31mFAIL\e[39m] Fail on starting environment."
    stop_environment
  fi

  exit
}

stop_environment() {
  echo -e "[\e[33mWAIT\e[39m] Stopping environment"
  docker compose -f docker-compose.yaml stop
  echo -e "[\e[32mOK\e[39m] Environment stopped"
  exit
}

clean_environment() {
  echo -e "[\e[33mWAIT\e[39m] Cleaning environment"
  docker compose down --remove-orphans -v
  echo -e "[\e[32mOK\e[39m] Environment cleaned"
  exit
}

handle_command "$1" "$2"